
spring:
  datasource:
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/security?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#mybatis&&通用Mapper
mybatis:
  type-aliases-package: com.lisheng.securitydemo.entity
  mapper-locations: classpath:mapper/*.xml
  mappers: com.lisheng.securitydemo.config.BaseMapper
  identity: MYSQL